FROM golang:1.9
MAINTAINER FandiYuan  <georgeyuan@diamondyuan.com>

RUN go get github.com/junzh0u/opendmm

copy / /opendmm/

RUN cd /opendmm && \
	CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build && \
	mv opendmm opendmm-s